name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup environment
      run: | 
          git clone https://github.com/mbrother2/butdr.git
          cd butdr
          mkdir zip; cd zip
          wget --quiet https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/game_4.4.0_4.5.0_hdiff_nodDY9LQAgruZ6Ns.zip
          mv game_4.4.0_4.5.0_hdiff_nodDY9LQAgruZ6Ns.zip old.zip 
          zip -r -s 1500m old.zip --out game_4.4.0_4.5.0_hdiff_nodDY9LQAgruZ6Ns.zip; rm old.zip
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
