name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup environment
      run: | 
          git clone https://github.com/mbrother2/butdr.git
          cd butdr 
          bash butdr.bash --setup
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
