name: CI
on: 
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup environment
      run: | 
          git clone https://github.com/mbrother2/butdr.git
          cd butdr
          mkdir zip; cd zip
          wget https://hw-pcdownload-qcloud.aki-game.net/pcstarter/prod/game/G153/1.1.0/4YLpI4sTRXwcCwfMypqr6oSMaffuFhZP/zip/Client/Content/Paks/pakchunk2-WindowsNoEditor.pak
          split -b -d 1500m pakchunk2-WindowsNoEditor.pak pakchunk2-WindowsNoEditor.pak-
          
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
