name: CI
on: 
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup environment
      run: | 
          git clone https://github.com/mbrother2/butdr.git
          cd butdr
          mkdir zip; cd zip
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
