name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup environment
      run: | 
          wget https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/game_4.4.0_4.5.0_hdiff_nodDY9LQAgruZ6Ns.zip
          git clone https://github.com/mbrother2/butdr.git
          cd butdr
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
